# Site settings
title: The Income Tax Illustrated
description: "How progressive is the federal income tax? How does it affect decisions about work, saving, and marriage? What is its effect on the U.S. economy?"
meta_image: cover-meta.jpg
url: "http://interactive.taxfoundation.org" # the base hostname & protocol for your site
baseurl: "/income-tax-illustrated"
permalink: :title
twitter_username: taxfoundation
# Setup and configure collection for chartbook slides
collections:
  - slides
# Build settings
markdown: kramdown
kramdown:
  input: GFM
