# Site settings
title: San Diego Illustrated
description: > # this means to ignore newlines until "baseurl:"
  Through a series of charts and maps, this book illustrates San Diego’s tax climate and economy, in an effort to depict the challenges faced by individuals, businesses, and policymakers.
meta_image: cover-meta.png
url: "http://interactive.taxfoundation.org" # the base hostname & protocol for your site
baseurl: "/san-diego-illustrated"
permalink: :title
twitter_username: taxfoundation
# Setup and configure collection for chartbook slides
collections:
  - slides
# Build settings
markdown: kramdown
kramdown:
  input: GFM
